// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NSrJtqN67JBrx8TGGazjTp8u92rkoqc',
    appId: '1:407151644931:web:5adcb8f66729ccdd4d1936',
    messagingSenderId: '407151644931',
    projectId: 'three-missions',
    authDomain: 'three-missions.firebaseapp.com',
    storageBucket: 'three-missions.firebasestorage.app',
    measurementId: 'G-CL31LQNY1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1JVWiMVLHyx3FPKSTtdQfo7EsyTitk0',
    appId: '1:407151644931:android:6a7e3b06084a93db4d1936',
    messagingSenderId: '407151644931',
    projectId: 'three-missions',
    storageBucket: 'three-missions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs1yR3JsngKieT8x2nukJct0DTliIOxoY',
    appId: '1:407151644931:ios:1ef99ae8d666cd304d1936',
    messagingSenderId: '407151644931',
    projectId: 'three-missions',
    storageBucket: 'three-missions.firebasestorage.app',
    iosBundleId: 'com.example.threeMissions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs1yR3JsngKieT8x2nukJct0DTliIOxoY',
    appId: '1:407151644931:ios:1ef99ae8d666cd304d1936',
    messagingSenderId: '407151644931',
    projectId: 'three-missions',
    storageBucket: 'three-missions.firebasestorage.app',
    iosBundleId: 'com.example.threeMissions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7NSrJtqN67JBrx8TGGazjTp8u92rkoqc',
    appId: '1:407151644931:web:932ffe9dbe5259914d1936',
    messagingSenderId: '407151644931',
    projectId: 'three-missions',
    authDomain: 'three-missions.firebaseapp.com',
    storageBucket: 'three-missions.firebasestorage.app',
    measurementId: 'G-QT72HRXGQB',
  );
}
